import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
    const { data, isLoading } = trpc.useQuery(["posts.all"]);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {isLoading ? (
                    <div>Loading...</div>
                ) : (
                    <div>{JSON.stringify(data, null, 2)}</div>
                )}
            </main>
        </div>
    );
};

export default Home;
