import type { NextPage } from "next";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { FormInput } from "../server/router/post";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
    const createPost = trpc.useMutation(["posts.create"]);
    const { handleSubmit, register, reset } = useForm<FormInput>();

    const submitForm = async (values: FormInput) => {
        try {
            await createPost.mutateAsync(values);
            reset();
        } catch (error) {
            console.error(error);
        }
    };

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className='w-screen flex flex-col items-center'>
                <h1>T3 App</h1>
                <p>Created using Create-T3-App</p>
                <form
                    className='justify-start flex flex-col container'
                    onSubmit={handleSubmit(submitForm)}>
                    <label>Post title</label>
                    <input
                        id='title'
                        type='text'
                        placeholder='title'
                        {...register("title")}
                    />
                    <label>Post content</label>
                    <textarea
                        id='content'
                        placeholder='content'
                        {...register("content")}
                    />
                    <button type='submit'>Submit</button>
                </form>
            </main>
        </>
    );
};

export default Home;
